AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This cloudformation script uses a custom AWS AMI to deploy an EC2 instance
  into a defined subnet & security group .
# Author = TERRY OBOT
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to connection to the host
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.medium
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
    
  EC2Subnet:
    Description: Subnet ID required to deploy EC2 instance
    Type: String
    Default: ""
    
  SourceSecurityGroupId:
    Description: security group to be used for access to ec2 instance
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: ""
    
  AMI:
    Description: The Id of the ami to be launched 
    Type: String
    Default: ""
    
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      UserData: !Base64
        Fn::Join:
        - ''
        - [IPAddress=, !Ref IPAddress]
      InstanceType: !Ref InstanceType
      SecurityGroupIds: !Ref SourceSecurityGroupId
      KeyName: !Ref KeyName
      ImageId: !Ref AMI
      SubnetId: !Ref EC2Subnet
      Tags:
        - Key: Name
          Value: Vista-Machine

  IPAddress:
    Type: AWS::EC2::EIP
    
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref IPAddress

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
    
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - AvailabilityZone
      
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName

  EC2InscanceElasticIP:
    Description: Elastic IP Address of the newly created EC2 Instance
    Value: !Ref IPAddress

